export const GOAL = [...Array.from({ length: 15 }, (_, index) => index + 1), 0]
export interface FifteenPuzzle { id: string; title: string; difficulty: 'easy'|'medium'|'hard'|'generated'; initialTiles: number[]; knownSolution: number[]; metadata: Record<string, unknown> }
export interface FifteenState { tiles: number[]; history: number[]; hintTile: number|null; hintCount: number; hintRoute: number[] }
export const sameTiles = (left:number[],right:number[]) => left.length===right.length&&left.every((value,index)=>value===right[index])
export function moveTile(tiles:number[],tile:number):number[]|null{if(tile===0)return null;const source=tiles.indexOf(tile),empty=tiles.indexOf(0);if(source<0||Math.abs(Math.floor(source/4)-Math.floor(empty/4))+Math.abs(source%4-empty%4)!==1)return null;const result=[...tiles];[result[source],result[empty]]=[result[empty],result[source]];return result}
export function initialGame(puzzle:FifteenPuzzle):FifteenState{return{tiles:[...puzzle.initialTiles],history:[],hintTile:null,hintCount:0,hintRoute:[]}}
export function move(state:FifteenState,tile:number):FifteenState{const tiles=moveTile(state.tiles,tile);if(!tiles)return state;const hintRoute=state.hintRoute[0]===tile?state.hintRoute.slice(1):[];return{...state,tiles,history:[...state.history,tile],hintTile:null,hintRoute}}
export function moveEmpty(state:FifteenState,rowDelta:number,columnDelta:number):FifteenState{const empty=state.tiles.indexOf(0),row=Math.floor(empty/4),column=empty%4,targetRow=row+rowDelta,targetColumn=column+columnDelta;if(targetRow<0||targetRow>=4||targetColumn<0||targetColumn>=4)return state;return move(state,state.tiles[targetRow*4+targetColumn])}
export function undo(state:FifteenState):FifteenState{if(!state.history.length)return state;const tile=state.history.at(-1)!,tiles=moveTile(state.tiles,tile)!;return{...state,tiles,history:state.history.slice(0,-1),hintTile:null,hintRoute:[]}}
export const isComplete=(state:FifteenState)=>sameTiles(state.tiles,GOAL)
export function nextHint(puzzle:FifteenPuzzle,state:FifteenState):FifteenState{if(isComplete(state)||state.hintTile!==null)return state;const route=state.hintRoute.length?state.hintRoute:[...state.history].reverse().concat(puzzle.knownSolution);if(!route.length)return state;return{...state,hintTile:route[0],hintCount:state.hintCount+1,hintRoute:route}}
export function restore(puzzle:FifteenPuzzle,state:FifteenState){let replay=[...puzzle.initialTiles];for(const tile of state.history){const moved=moveTile(replay,tile);if(!moved)throw new Error('保存履歴に不正な移動があります。');replay=moved}if(!sameTiles(replay,state.tiles))throw new Error('保存状態と操作履歴が一致しません。');if(state.hintCount<0||!Number.isInteger(state.hintCount))throw new Error('ヒント状態が不正です。');return state}
