export const UP=1,RIGHT=2,DOWN=4,LEFT=8
export interface Position{row:number;column:number}
export interface MazePuzzle{id:string;title:string;difficulty:'easy'|'medium'|'hard'|'generated';width:number;height:number;passages:number[];start:Position;goal:Position;answerPath:Position[];metadata:Record<string,unknown>}
export interface MazeState{history:Position[];hintPosition:Position|null;hintCount:number}
export const DIRECTIONS=[{dr:-1,dc:0,bit:UP,opposite:DOWN,code:'U'},{dr:0,dc:1,bit:RIGHT,opposite:LEFT,code:'R'},{dr:1,dc:0,bit:DOWN,opposite:UP,code:'D'},{dr:0,dc:-1,bit:LEFT,opposite:RIGHT,code:'L'}] as const
export const samePosition=(a:Position,b:Position)=>a.row===b.row&&a.column===b.column
export const keyOf=(position:Position)=>`${position.row},${position.column}`
export function neighbors(puzzle:Pick<MazePuzzle,'width'|'height'|'passages'>,position:Position){const mask=puzzle.passages[position.row*puzzle.width+position.column],result:{position:Position;code:string}[]=[];for(const direction of DIRECTIONS){const row=position.row+direction.dr,column=position.column+direction.dc;if((mask&direction.bit)&&row>=0&&row<puzzle.height&&column>=0&&column<puzzle.width)result.push({position:{row,column},code:direction.code})}return result}
export function solutionPath(puzzle:Pick<MazePuzzle,'width'|'height'|'passages'>,start:Position,goal:Position):Position[]{const queue=[start],previous=new Map<string,Position|null>([[keyOf(start),null]]);for(let index=0;index<queue.length;index++){const current=queue[index];if(samePosition(current,goal))break;for(const{position}of neighbors(puzzle,current))if(!previous.has(keyOf(position))){previous.set(keyOf(position),current);queue.push(position)}}if(!previous.has(keyOf(goal)))return[];const path:Position[]=[];let current:Position|null=goal;while(current){path.push(current);current=previous.get(keyOf(current))??null}return path.reverse()}
export function pathFromCodes(start:Position,codes:string){const path=[start];for(const code of codes){const direction=DIRECTIONS.find(item=>item.code===code);if(!direction)throw new Error('解答経路に不正な方向があります。');const last=path.at(-1)!;path.push({row:last.row+direction.dr,column:last.column+direction.dc})}return path}
export function pathCodes(path:Position[]){return path.slice(1).map((position,index)=>{const previous=path[index],direction=DIRECTIONS.find(item=>previous.row+item.dr===position.row&&previous.column+item.dc===position.column);if(!direction)throw new Error('経路に隣接しない位置があります。');return direction.code}).join('')}
export const initialGame=(puzzle:MazePuzzle):MazeState=>({history:[puzzle.start],hintPosition:null,hintCount:0})
export const currentPosition=(state:MazeState)=>state.history.at(-1)!
export const isComplete=(puzzle:MazePuzzle,state:MazeState)=>samePosition(currentPosition(state),puzzle.goal)
export function moveTo(puzzle:MazePuzzle,state:MazeState,target:Position):MazeState{if(isComplete(puzzle,state)||!neighbors(puzzle,currentPosition(state)).some(item=>samePosition(item.position,target)))return state;return{...state,history:[...state.history,target],hintPosition:null}}
export function moveDirection(puzzle:MazePuzzle,state:MazeState,dr:number,dc:number){const current=currentPosition(state);return moveTo(puzzle,state,{row:current.row+dr,column:current.column+dc})}
export function undo(state:MazeState){if(state.history.length<=1)return state;return{...state,history:state.history.slice(0,-1),hintPosition:null}}
export function nextHint(puzzle:MazePuzzle,state:MazeState):MazeState{if(isComplete(puzzle,state)||state.hintPosition)return state;const route=solutionPath(puzzle,currentPosition(state),puzzle.goal);if(route.length<2)return state;return{...state,hintPosition:route[1],hintCount:state.hintCount+1}}
export function restore(puzzle:MazePuzzle,state:MazeState){if(!state.history.length||!samePosition(state.history[0],puzzle.start)||!Number.isInteger(state.hintCount)||state.hintCount<0)throw new Error('保存状態が不正です。');let replay=initialGame(puzzle);for(const position of state.history.slice(1)){const moved=moveTo(puzzle,replay,position);if(moved===replay)throw new Error('保存履歴に不正な移動があります。');replay=moved}if(state.hintPosition){const route=solutionPath(puzzle,currentPosition(state),puzzle.goal);if(state.hintCount<1||route.length<2||!samePosition(route[1],state.hintPosition))throw new Error('保存ヒントが不正です。')}return state}
