export interface GuessResult{code:number[];exact:number;misplaced:number}
export interface MastermindPuzzle{id:string;title:string;difficulty:'easy'|'medium'|'hard'|'generated';codeLength:number;symbolCount:number;allowDuplicates:boolean;maxAttempts:number;secret:number[];metadata:Record<string,unknown>}
export interface MastermindState{current:(number|null)[];selected:number;guesses:GuessResult[];revealed:Record<number,number>;hintCount:number;lastCandidateRevision:[number,number]|null}
export function scoreGuess(secret:number[],guess:number[]):[number,number]{let exact=0,matched=0;const secretCounts=new Map<number,number>(),guessCounts=new Map<number,number>();secret.forEach((value,index)=>{if(value===guess[index])exact++;secretCounts.set(value,(secretCounts.get(value)??0)+1)});guess.forEach(value=>guessCounts.set(value,(guessCounts.get(value)??0)+1));for(const[value,count]of secretCounts)matched+=Math.min(count,guessCounts.get(value)??0);return[exact,matched-exact]}
export const initialGame=(puzzle:MastermindPuzzle):MastermindState=>({current:Array(puzzle.codeLength).fill(null),selected:0,guesses:[],revealed:{},hintCount:0,lastCandidateRevision:null})
export const isWon=(puzzle:MastermindPuzzle,state:MastermindState)=>state.guesses.at(-1)?.exact===puzzle.codeLength
export const isLost=(puzzle:MastermindPuzzle,state:MastermindState)=>state.guesses.length>=puzzle.maxAttempts&&!isWon(puzzle,state)
export const isFinished=(puzzle:MastermindPuzzle,state:MastermindState)=>isWon(puzzle,state)||isLost(puzzle,state)
export function selectPosition(puzzle:MastermindPuzzle,state:MastermindState,index:number){return index>=0&&index<puzzle.codeLength?{...state,selected:index}:state}
export function setSymbol(puzzle:MastermindPuzzle,state:MastermindState,value:number):MastermindState{if(isFinished(puzzle,state)||state.revealed[state.selected]!==undefined||value<1||value>puzzle.symbolCount)return state;if(!puzzle.allowDuplicates&&state.current.includes(value)&&state.current[state.selected]!==value)return state;const current=[...state.current];current[state.selected]=value;let selected=state.selected;for(let index=state.selected+1;index<puzzle.codeLength;index++)if(state.revealed[index]===undefined&&current[index]===null){selected=index;break}return{...state,current,selected}}
export function clearSelected(puzzle:MastermindPuzzle,state:MastermindState){if(isFinished(puzzle,state)||state.revealed[state.selected]!==undefined||state.current[state.selected]===null)return state;const current=[...state.current];current[state.selected]=null;return{...state,current}}
export function submitGuess(puzzle:MastermindPuzzle,state:MastermindState):MastermindState{if(isFinished(puzzle,state)||state.current.some(value=>value===null))return state;const code=state.current as number[],[exact,misplaced]=scoreGuess(puzzle.secret,code),guesses=[...state.guesses,{code:[...code],exact,misplaced}],current=Array.from({length:puzzle.codeLength},(_,index)=>state.revealed[index]??null),selected=Array.from({length:puzzle.codeLength},(_,index)=>index).find(index=>state.revealed[index]===undefined)??0;return{...state,current,selected,guesses}}
export function revealPosition(puzzle:MastermindPuzzle,state:MastermindState,index=state.selected){if(isFinished(puzzle,state)||index<0||index>=puzzle.codeLength||state.revealed[index]!==undefined)return state;const revealed={...state.revealed,[index]:puzzle.secret[index]},current=[...state.current];current[index]=puzzle.secret[index];return{...state,revealed,current,hintCount:state.hintCount+1}}
function* codes(puzzle:MastermindPuzzle,prefix:number[]=[]):Generator<number[]>{if(prefix.length===puzzle.codeLength){yield prefix;return}for(let value=1;value<=puzzle.symbolCount;value++){if(!puzzle.allowDuplicates&&prefix.includes(value))continue;yield*codes(puzzle,[...prefix,value])}}
export function candidateCount(puzzle:MastermindPuzzle,state:MastermindState){let count=0;for(const candidate of codes(puzzle)){if(Object.entries(state.revealed).some(([index,value])=>candidate[Number(index)]!==value))continue;if(state.guesses.every(result=>{const[exact,misplaced]=scoreGuess(candidate,result.code);return exact===result.exact&&misplaced===result.misplaced}))count++}const revision:[number,number]=[state.guesses.length,Object.keys(state.revealed).length],counted=!state.lastCandidateRevision||state.lastCandidateRevision[0]!==revision[0]||state.lastCandidateRevision[1]!==revision[1];return{count,counted,state:{...state,hintCount:state.hintCount+(counted?1:0),lastCandidateRevision:revision} as MastermindState}}
export function restore(puzzle:MastermindPuzzle,state:MastermindState){if(state.current.length!==puzzle.codeLength||state.selected<0||state.selected>=puzzle.codeLength||state.guesses.length>puzzle.maxAttempts||state.hintCount<0)throw new Error('保存状態が不正です。');for(const result of state.guesses){const[exact,misplaced]=scoreGuess(puzzle.secret,result.code);if(result.code.length!==puzzle.codeLength||exact!==result.exact||misplaced!==result.misplaced)throw new Error('保存履歴が不正です。')}for(const[index,value]of Object.entries(state.revealed))if(puzzle.secret[Number(index)]!==value||state.current[Number(index)]!==value)throw new Error('公開位置が不正です。');return state}
