export type Difficulty = "easy" | "medium" | "generated";
export type Direction = "left" | "right" | "top" | "bottom";
export type InputMode = "value" | "note";
export interface SkyscraperClues { top:number[]; right:number[]; bottom:number[]; left:number[] }
export interface SkyscraperPuzzle { id:string; title:string; difficulty:Difficulty; size:4|5; clues:SkyscraperClues; givens:number[]; solution:number[]; generated?:boolean }
export type HypothesisAxis = "row" | "column";
export interface HypothesisLine { axis:HypothesisAxis; unit:number }
export interface HypothesisState { trialValues:number[]; history:number[][]; selectedLine:HypothesisLine|null }
export interface SkyscraperState { values:number[]; notes:number[][]; selected:number|null; inputMode:InputMode; hinted:number[]; hintCount:number; hypothesis:HypothesisState|null }
export type MarkerState = "confirmed" | "provisional";

const permutationCache=new Map<number,number[][]>();
export function permutations(size:number){const cached=permutationCache.get(size);if(cached)return cached;const result:number[][]=[];const visit=(prefix:number[],remaining:number[])=>{if(!remaining.length)result.push(prefix);else remaining.forEach((value,index)=>visit([...prefix,value],[...remaining.slice(0,index),...remaining.slice(index+1)]))};visit([],Array.from({length:size},(_,i)=>i+1));permutationCache.set(size,result);return result}
export function visibleCount(line:number[]){let highest=0,count=0;for(const value of line)if(value>highest){highest=value;count++}return count}
export const clueMatches=(line:number[],clue:number)=>clue===0||visibleCount(line)===clue;
export function lineCandidates(line:number[],nearClue:number,farClue:number){return permutations(line.length).filter(candidate=>candidate.every((value,index)=>line[index]===0||line[index]===value)&&clueMatches(candidate,nearClue)&&clueMatches([...candidate].reverse(),farClue))}
export function lineIndices(size:number,direction:Direction,unit:number){const forward=Array.from({length:size},(_,offset)=>direction==="left"||direction==="right"?unit*size+offset:offset*size+unit);return direction==="right"||direction==="bottom"?forward.reverse():forward}
export const clueFor=(puzzle:SkyscraperPuzzle,direction:Direction,unit:number)=>puzzle.clues[direction][unit];
export function oppositeClue(puzzle:SkyscraperPuzzle,direction:Direction,unit:number){const opposite:Record<Direction,Direction>={left:"right",right:"left",top:"bottom",bottom:"top"};return puzzle.clues[opposite[direction]][unit]}
export function visibilityMarkers(values:number[],size:number,direction:Direction,unit:number){const indices=lineIndices(size,direction,unit);let highest=0,gap=false;const result=new Map<number,MarkerState>();for(const index of indices){const value=values[index];if(!value){gap=true;continue}if(value>highest){result.set(index,gap?"provisional":"confirmed");highest=value}}return result}
export const row=(values:number[],size:number,rowIndex:number)=>values.slice(rowIndex*size,(rowIndex+1)*size);
export const column=(values:number[],size:number,columnIndex:number)=>Array.from({length:size},(_,rowIndex)=>values[rowIndex*size+columnIndex]);
export function conflicts(values:number[],size:number){const result=new Set<number>();for(let unit=0;unit<size;unit++)for(const indices of[lineIndices(size,"left",unit),lineIndices(size,"top",unit)]){const positions=new Map<number,number[]>();indices.forEach(index=>{const value=values[index];if(value)positions.set(value,[...(positions.get(value)??[]),index])});positions.forEach(items=>{if(items.length>1)items.forEach(index=>result.add(index))})}return result}
export function lineStatus(puzzle:SkyscraperPuzzle,values:number[],direction:Direction,unit:number){const line=lineIndices(puzzle.size,direction,unit).map(index=>values[index]),found=lineCandidates(line,clueFor(puzzle,direction,unit),oppositeClue(puzzle,direction,unit));if(!found.length)return "impossible" as const;return line.every(Boolean)?"satisfied" as const:"open" as const}
export function candidates(puzzle:SkyscraperPuzzle,values:number[],index:number){if(values[index])return[];const size=puzzle.size,rowIndex=Math.floor(index/size),columnIndex=index%size,rows=lineCandidates(row(values,size,rowIndex),puzzle.clues.left[rowIndex],puzzle.clues.right[rowIndex]),columns=lineCandidates(column(values,size,columnIndex),puzzle.clues.top[columnIndex],puzzle.clues.bottom[columnIndex]);return Array.from({length:size},(_,i)=>i+1).filter(value=>rows.some(candidate=>candidate[columnIndex]===value)&&columns.some(candidate=>candidate[rowIndex]===value))}
export function initialSkyscraper(puzzle:SkyscraperPuzzle):SkyscraperState{return{values:[...puzzle.givens],notes:Array.from({length:puzzle.size**2},()=>[]),selected:null,inputMode:"value",hinted:[],hintCount:0,hypothesis:null}}
export const isFixed=(puzzle:SkyscraperPuzzle,state:SkyscraperState,index:number)=>puzzle.givens[index]!==0||state.hinted.includes(index);
export function enterNumber(puzzle:SkyscraperPuzzle,state:SkyscraperState,value:number){const index=state.selected;if(index===null||isFixed(puzzle,state,index)||value<1||value>puzzle.size)return state;const notes=state.notes.map(item=>[...item]);if(state.inputMode==="note"){if(state.values[index])return state;const set=new Set(notes[index]);if(set.has(value))set.delete(value);else set.add(value);notes[index]=[...set].sort();return{...state,notes}}const values=[...state.values];values[index]=value;notes[index]=[];const rowIndex=Math.floor(index/puzzle.size),columnIndex=index%puzzle.size;[...lineIndices(puzzle.size,"left",rowIndex),...lineIndices(puzzle.size,"top",columnIndex)].forEach(peer=>{if(peer!==index)notes[peer]=notes[peer].filter(digit=>digit!==value)});return{...state,values,notes}}
export function clearCell(puzzle:SkyscraperPuzzle,state:SkyscraperState){if(state.selected===null||isFixed(puzzle,state,state.selected))return state;const values=[...state.values],notes=state.notes.map(item=>[...item]);values[state.selected]=0;notes[state.selected]=[];return{...state,values,notes}}
export function addCandidateNotes(puzzle:SkyscraperPuzzle,state:SkyscraperState){if(state.selected===null||state.values[state.selected])return state;const notes=state.notes.map(item=>[...item]);notes[state.selected]=candidates(puzzle,state.values,state.selected);return{...state,notes}}
export function cleanCandidateNotes(puzzle:SkyscraperPuzzle,state:SkyscraperState){let removed=0;const notes=state.notes.map((item,index)=>{const allowed=new Set(candidates(puzzle,state.values,index)),next=item.filter(value=>allowed.has(value));removed+=item.length-next.length;return next});return{state:removed?{...state,notes}:state,removed}}
export function revealHint(puzzle:SkyscraperPuzzle,state:SkyscraperState){const eligible=state.values.map((value,index)=>({value,index})).filter(({value,index})=>!isFixed(puzzle,state,index)&&value!==puzzle.solution[index]);if(!eligible.length)return state;const preferred=eligible.find(({index})=>index===state.selected)??eligible[0],values=[...state.values],notes=state.notes.map(item=>[...item]);values[preferred.index]=puzzle.solution[preferred.index];notes[preferred.index]=[];return{...state,values,notes,selected:preferred.index,hinted:[...state.hinted,preferred.index],hintCount:state.hintCount+1}}
export function findLogicalHint(puzzle:SkyscraperPuzzle,values:number[]){for(let index=0;index<values.length;index++){const found=candidates(puzzle,values,index);if(found.length===1)return{index,value:found[0]}}return null}
export function isComplete(puzzle:SkyscraperPuzzle,state:SkyscraperState){if(state.values.some(value=>!value)||conflicts(state.values,puzzle.size).size)return false;for(const direction of["left","right","top","bottom"]as Direction[])for(let unit=0;unit<puzzle.size;unit++)if(lineStatus(puzzle,state.values,direction,unit)!=="satisfied")return false;return true}
export function countSolutions(puzzle:Pick<SkyscraperPuzzle,"size"|"clues"|"givens">,limit=2){const values=[...puzzle.givens],size=puzzle.size;let count=0;const compatible=(direction:Direction,unit:number)=>{const line=lineIndices(size,direction,unit).map(index=>values[index]),opposite:Record<Direction,Direction>={left:"right",right:"left",top:"bottom",bottom:"top"};return lineCandidates(line,puzzle.clues[direction][unit],puzzle.clues[opposite[direction]][unit]).length>0};const visit=()=>{if(count>=limit)return;let best=-1,options:number[]=[];for(let index=0;index<values.length;index++)if(!values[index]){const r=Math.floor(index/size),c=index%size,used=new Set([...row(values,size,r),...column(values,size,c)]),found=Array.from({length:size},(_,i)=>i+1).filter(value=>!used.has(value));if(best<0||found.length<options.length){best=index;options=found;if(found.length<=1)break}}if(best<0){count++;return}const r=Math.floor(best/size),c=best%size;for(const value of options){values[best]=value;if(compatible("left",r)&&compatible("top",c))visit();values[best]=0;if(count>=limit)return}};visit();return count}

export const workingValues=(state:SkyscraperState)=>state.values.map((value,index)=>value||state.hypothesis?.trialValues[index]||0);
export function startHypothesis(state:SkyscraperState){if(state.hypothesis)return state;return{...state,inputMode:"value" as const,hypothesis:{trialValues:Array(state.values.length).fill(0),history:[],selectedLine:null}}}
export function discardHypothesis(state:SkyscraperState){return state.hypothesis?{...state,hypothesis:null}:state}
export function selectHypothesisLine(state:SkyscraperState,selectedLine:HypothesisLine){if(!state.hypothesis)return state;return{...state,hypothesis:{...state.hypothesis,selectedLine}}}
function lineNotesMatch(candidate:number[],indices:number[],notes:number[][],values:number[]){return candidate.every((value,offset)=>values[indices[offset]]!==0||notes[indices[offset]].length===0||notes[indices[offset]].includes(value))}
function lineDomain(puzzle:SkyscraperPuzzle,values:number[],notes:number[][],axis:HypothesisAxis,unit:number){const direction=axis==="row"?"left":"top",indices=lineIndices(puzzle.size,direction,unit),line=indices.map(index=>values[index]),near=axis==="row"?puzzle.clues.left[unit]:puzzle.clues.top[unit],far=axis==="row"?puzzle.clues.right[unit]:puzzle.clues.bottom[unit];return lineCandidates(line,near,far).filter(candidate=>lineNotesMatch(candidate,indices,notes,values))}
export function hypothesisSequences(puzzle:SkyscraperPuzzle,state:SkyscraperState,line:HypothesisLine){const values=workingValues(state),indices=lineIndices(puzzle.size,line.axis==="row"?"left":"top",line.unit);return lineDomain(puzzle,values,state.notes,line.axis,line.unit).filter(sequence=>{const next=[...values];indices.forEach((index,offset)=>{if(!state.values[index])next[index]=sequence[offset]});const crossAxis=line.axis==="row"?"column":"row";return indices.every(index=>lineDomain(puzzle,next,state.notes,crossAxis,line.axis==="row"?index%puzzle.size:Math.floor(index/puzzle.size)).length>0)})}
function pushTrial(state:SkyscraperState,trialValues:number[]){if(!state.hypothesis)return state;return{...state,hypothesis:{...state.hypothesis,trialValues,history:[...state.hypothesis.history,[...state.hypothesis.trialValues]]}}}
export function applyHypothesisSequence(puzzle:SkyscraperPuzzle,state:SkyscraperState,line:HypothesisLine,sequence:number[]){if(!state.hypothesis||sequence.length!==puzzle.size)return state;const trial=[...state.hypothesis.trialValues],indices=lineIndices(puzzle.size,line.axis==="row"?"left":"top",line.unit);indices.forEach((index,offset)=>{if(!state.values[index])trial[index]=sequence[offset]});return pushTrial(selectHypothesisLine(state,line),trial)}
export function enterHypothesisNumber(puzzle:SkyscraperPuzzle,state:SkyscraperState,value:number){if(!state.hypothesis||state.selected===null||state.values[state.selected]||value<1||value>puzzle.size)return state;const trial=[...state.hypothesis.trialValues];trial[state.selected]=value;return pushTrial(state,trial)}
export function clearHypothesisCell(state:SkyscraperState){if(!state.hypothesis||state.selected===null||!state.hypothesis.trialValues[state.selected])return state;const trial=[...state.hypothesis.trialValues];trial[state.selected]=0;return pushTrial(state,trial)}
export function applyHypothesisValues(state:SkyscraperState,assignments:{index:number;value:number}[]){if(!state.hypothesis||!assignments.length)return state;const trial=[...state.hypothesis.trialValues];assignments.forEach(({index,value})=>{if(!state.values[index])trial[index]=value});return pushTrial(state,trial)}
export function undoHypothesis(state:SkyscraperState){if(!state.hypothesis?.history.length)return state;const history=[...state.hypothesis.history],trialValues=history.pop()!;return{...state,hypothesis:{...state.hypothesis,history,trialValues}}}
export function resetHypothesis(state:SkyscraperState){if(!state.hypothesis)return state;return{...state,hypothesis:{...state.hypothesis,trialValues:Array(state.values.length).fill(0),history:[]}}}
export function commitHypothesis(state:SkyscraperState){if(!state.hypothesis)return state;const values=workingValues(state),notes=state.notes.map((note,index)=>values[index]?[]:[...note]);return{...state,values,notes,hypothesis:null}}
export interface HypothesisAnalysis { rowDomains:number[][][]; columnDomains:number[][][]; forced:{index:number;value:number}[]; contradiction:HypothesisLine|null }
export function analyzeHypothesis(puzzle:SkyscraperPuzzle,state:SkyscraperState):HypothesisAnalysis{const values=workingValues(state),rows=Array.from({length:puzzle.size},(_,unit)=>lineDomain(puzzle,values,state.notes,"row",unit)),columns=Array.from({length:puzzle.size},(_,unit)=>lineDomain(puzzle,values,state.notes,"column",unit));let changed=true;while(changed){changed=false;for(let r=0;r<puzzle.size;r++){const next=rows[r].filter(sequence=>sequence.every((value,c)=>columns[c].some(candidate=>candidate[r]===value)));if(next.length!==rows[r].length){rows[r]=next;changed=true}}for(let c=0;c<puzzle.size;c++){const next=columns[c].filter(sequence=>sequence.every((value,r)=>rows[r].some(candidate=>candidate[c]===value)));if(next.length!==columns[c].length){columns[c]=next;changed=true}}}const badRow=rows.findIndex(domain=>domain.length===0),badColumn=columns.findIndex(domain=>domain.length===0);const contradiction=badRow>=0?{axis:"row" as const,unit:badRow}:badColumn>=0?{axis:"column" as const,unit:badColumn}:null,forced:{index:number;value:number}[]=[];if(!contradiction)for(let index=0;index<values.length;index++)if(!values[index]){const r=Math.floor(index/puzzle.size),c=index%puzzle.size,possible=new Set(rows[r].map(sequence=>sequence[c]).filter(value=>columns[c].some(sequence=>sequence[r]===value)));if(possible.size===1)forced.push({index,value:[...possible][0]})}return{rowDomains:rows,columnDomains:columns,forced,contradiction}}
export function countCompletions(puzzle:SkyscraperPuzzle,state:SkyscraperState,limit=1){const values=workingValues(state),copy:{size:4|5;clues:SkyscraperClues;givens:number[]}={size:puzzle.size,clues:puzzle.clues,givens:values};return countSolutions(copy,limit)}
