export type Difficulty = "easy" | "medium" | "generated";
export type Direction = "left" | "right" | "top" | "bottom";
export type InputMode = "value" | "note";
export interface SkyscraperClues { top:number[]; right:number[]; bottom:number[]; left:number[] }
export interface SkyscraperPuzzle { id:string; title:string; difficulty:Difficulty; size:4|5; clues:SkyscraperClues; givens:number[]; solution:number[]; generated?:boolean }
export interface SkyscraperState { values:number[]; notes:number[][]; selected:number|null; inputMode:InputMode; hinted:number[]; hintCount:number }
export type MarkerState = "confirmed" | "provisional";

const permutationCache=new Map<number,number[][]>();
export function permutations(size:number){const cached=permutationCache.get(size);if(cached)return cached;const result:number[][]=[];const visit=(prefix:number[],remaining:number[])=>{if(!remaining.length)result.push(prefix);else remaining.forEach((value,index)=>visit([...prefix,value],[...remaining.slice(0,index),...remaining.slice(index+1)]))};visit([],Array.from({length:size},(_,i)=>i+1));permutationCache.set(size,result);return result}
export function visibleCount(line:number[]){let highest=0,count=0;for(const value of line)if(value>highest){highest=value;count++}return count}
export const clueMatches=(line:number[],clue:number)=>clue===0||visibleCount(line)===clue;
export function lineCandidates(line:number[],nearClue:number,farClue:number){return permutations(line.length).filter(candidate=>candidate.every((value,index)=>line[index]===0||line[index]===value)&&clueMatches(candidate,nearClue)&&clueMatches([...candidate].reverse(),farClue))}
export function lineIndices(size:number,direction:Direction,unit:number){const forward=Array.from({length:size},(_,offset)=>direction==="left"||direction==="right"?unit*size+offset:offset*size+unit);return direction==="right"||direction==="bottom"?forward.reverse():forward}
export const clueFor=(puzzle:SkyscraperPuzzle,direction:Direction,unit:number)=>puzzle.clues[direction][unit];
export function oppositeClue(puzzle:SkyscraperPuzzle,direction:Direction,unit:number){const opposite:Record<Direction,Direction>={left:"right",right:"left",top:"bottom",bottom:"top"};return puzzle.clues[opposite[direction]][unit]}
export function visibilityMarkers(values:number[],size:number,direction:Direction,unit:number){const indices=lineIndices(size,direction,unit);let highest=0,gap=false;const result=new Map<number,MarkerState>();for(const index of indices){const value=values[index];if(!value){gap=true;continue}if(value>highest){result.set(index,gap?"provisional":"confirmed");highest=value}}return result}
export const row=(values:number[],size:number,rowIndex:number)=>values.slice(rowIndex*size,(rowIndex+1)*size);
export const column=(values:number[],size:number,columnIndex:number)=>Array.from({length:size},(_,rowIndex)=>values[rowIndex*size+columnIndex]);
export function conflicts(values:number[],size:number){const result=new Set<number>();for(let unit=0;unit<size;unit++)for(const indices of[lineIndices(size,"left",unit),lineIndices(size,"top",unit)]){const positions=new Map<number,number[]>();indices.forEach(index=>{const value=values[index];if(value)positions.set(value,[...(positions.get(value)??[]),index])});positions.forEach(items=>{if(items.length>1)items.forEach(index=>result.add(index))})}return result}
export function lineStatus(puzzle:SkyscraperPuzzle,values:number[],direction:Direction,unit:number){const line=lineIndices(puzzle.size,direction,unit).map(index=>values[index]),found=lineCandidates(line,clueFor(puzzle,direction,unit),oppositeClue(puzzle,direction,unit));if(!found.length)return "impossible" as const;return line.every(Boolean)?"satisfied" as const:"open" as const}
export function candidates(puzzle:SkyscraperPuzzle,values:number[],index:number){if(values[index])return[];const size=puzzle.size,rowIndex=Math.floor(index/size),columnIndex=index%size,rows=lineCandidates(row(values,size,rowIndex),puzzle.clues.left[rowIndex],puzzle.clues.right[rowIndex]),columns=lineCandidates(column(values,size,columnIndex),puzzle.clues.top[columnIndex],puzzle.clues.bottom[columnIndex]);return Array.from({length:size},(_,i)=>i+1).filter(value=>rows.some(candidate=>candidate[columnIndex]===value)&&columns.some(candidate=>candidate[rowIndex]===value))}
export function initialSkyscraper(puzzle:SkyscraperPuzzle):SkyscraperState{return{values:[...puzzle.givens],notes:Array.from({length:puzzle.size**2},()=>[]),selected:null,inputMode:"value",hinted:[],hintCount:0}}
export const isFixed=(puzzle:SkyscraperPuzzle,state:SkyscraperState,index:number)=>puzzle.givens[index]!==0||state.hinted.includes(index);
export function enterNumber(puzzle:SkyscraperPuzzle,state:SkyscraperState,value:number){const index=state.selected;if(index===null||isFixed(puzzle,state,index)||value<1||value>puzzle.size)return state;const notes=state.notes.map(item=>[...item]);if(state.inputMode==="note"){if(state.values[index])return state;const set=new Set(notes[index]);if(set.has(value))set.delete(value);else set.add(value);notes[index]=[...set].sort();return{...state,notes}}const values=[...state.values];values[index]=value;notes[index]=[];const rowIndex=Math.floor(index/puzzle.size),columnIndex=index%puzzle.size;[...lineIndices(puzzle.size,"left",rowIndex),...lineIndices(puzzle.size,"top",columnIndex)].forEach(peer=>{if(peer!==index)notes[peer]=notes[peer].filter(digit=>digit!==value)});return{...state,values,notes}}
export function clearCell(puzzle:SkyscraperPuzzle,state:SkyscraperState){if(state.selected===null||isFixed(puzzle,state,state.selected))return state;const values=[...state.values],notes=state.notes.map(item=>[...item]);values[state.selected]=0;notes[state.selected]=[];return{...state,values,notes}}
export function addCandidateNotes(puzzle:SkyscraperPuzzle,state:SkyscraperState){if(state.selected===null||state.values[state.selected])return state;const notes=state.notes.map(item=>[...item]);notes[state.selected]=candidates(puzzle,state.values,state.selected);return{...state,notes}}
export function cleanCandidateNotes(puzzle:SkyscraperPuzzle,state:SkyscraperState){let removed=0;const notes=state.notes.map((item,index)=>{const allowed=new Set(candidates(puzzle,state.values,index)),next=item.filter(value=>allowed.has(value));removed+=item.length-next.length;return next});return{state:removed?{...state,notes}:state,removed}}
export function revealHint(puzzle:SkyscraperPuzzle,state:SkyscraperState){const eligible=state.values.map((value,index)=>({value,index})).filter(({value,index})=>!isFixed(puzzle,state,index)&&value!==puzzle.solution[index]);if(!eligible.length)return state;const preferred=eligible.find(({index})=>index===state.selected)??eligible[0],values=[...state.values],notes=state.notes.map(item=>[...item]);values[preferred.index]=puzzle.solution[preferred.index];notes[preferred.index]=[];return{...state,values,notes,selected:preferred.index,hinted:[...state.hinted,preferred.index],hintCount:state.hintCount+1}}
export function findLogicalHint(puzzle:SkyscraperPuzzle,values:number[]){for(let index=0;index<values.length;index++){const found=candidates(puzzle,values,index);if(found.length===1)return{index,value:found[0]}}return null}
export function isComplete(puzzle:SkyscraperPuzzle,state:SkyscraperState){if(state.values.some(value=>!value)||conflicts(state.values,puzzle.size).size)return false;for(const direction of["left","right","top","bottom"]as Direction[])for(let unit=0;unit<puzzle.size;unit++)if(lineStatus(puzzle,state.values,direction,unit)!=="satisfied")return false;return true}
export function countSolutions(puzzle:Pick<SkyscraperPuzzle,"size"|"clues"|"givens">,limit=2){const values=[...puzzle.givens],size=puzzle.size;let count=0;const compatible=(direction:Direction,unit:number)=>{const line=lineIndices(size,direction,unit).map(index=>values[index]),opposite:Record<Direction,Direction>={left:"right",right:"left",top:"bottom",bottom:"top"};return lineCandidates(line,puzzle.clues[direction][unit],puzzle.clues[opposite[direction]][unit]).length>0};const visit=()=>{if(count>=limit)return;let best=-1,options:number[]=[];for(let index=0;index<values.length;index++)if(!values[index]){const r=Math.floor(index/size),c=index%size,used=new Set([...row(values,size,r),...column(values,size,c)]),found=Array.from({length:size},(_,i)=>i+1).filter(value=>!used.has(value));if(best<0||found.length<options.length){best=index;options=found;if(found.length<=1)break}}if(best<0){count++;return}const r=Math.floor(best/size),c=best%size;for(const value of options){values[best]=value;if(compatible("left",r)&&compatible("top",c))visit();values[best]=0;if(count>=limit)return}};visit();return count}
