export type Difficulty='easy'|'medium'|'hard'|'generated'
export interface SudokuPuzzle{id:string;title:string;difficulty:Difficulty;givens:number[];solution:number[];generated?:boolean;estimatedDifficulty?:string}
export type InputMode='value'|'note'
export interface SudokuState{values:number[];notes:number[][];selected:number|null;inputMode:InputMode;hinted:number[];hintCount:number;lightHint:{index:number;candidates:number[];signature:string}|null}

export const peers=(index:number)=>{const row=Math.floor(index/9),column=index%9,blockRow=Math.floor(row/3)*3,blockColumn=Math.floor(column/3)*3,result=new Set<number>();for(let n=0;n<9;n++){result.add(row*9+n);result.add(n*9+column)}for(let r=blockRow;r<blockRow+3;r++)for(let c=blockColumn;c<blockColumn+3;c++)result.add(r*9+c);result.delete(index);return [...result]}
export function initialSudoku(puzzle:SudokuPuzzle):SudokuState{return{values:[...puzzle.givens],notes:Array.from({length:81},()=>[]),selected:null,inputMode:'value',hinted:[],hintCount:0,lightHint:null}}
export const isFixed=(puzzle:SudokuPuzzle,state:SudokuState,index:number)=>puzzle.givens[index]!==0||state.hinted.includes(index)
export function candidates(values:number[],index:number){if(values[index])return[];const used=new Set(peers(index).map(i=>values[i]).filter(Boolean));return Array.from({length:9},(_,i)=>i+1).filter(n=>!used.has(n))}
export function conflicts(values:number[]){const result=new Set<number>();for(let i=0;i<81;i++){if(!values[i])continue;for(const peer of peers(i))if(values[peer]===values[i]){result.add(i);result.add(peer)}}return result}
export const isComplete=(state:SudokuState)=>state.values.every(Boolean)&&conflicts(state.values).size===0
export function selectCell(state:SudokuState,index:number){return state.selected===index?state:{...state,selected:index,lightHint:null}}
export function setMode(state:SudokuState,inputMode:InputMode){return{...state,inputMode}}
export function enterNumber(puzzle:SudokuPuzzle,state:SudokuState,value:number){const index=state.selected;if(index===null||isFixed(puzzle,state,index)||value<1||value>9)return state;if(state.inputMode==='note'){if(state.values[index])return state;const notes=state.notes.map(list=>[...list]),set=new Set(notes[index]);if(set.has(value))set.delete(value);else set.add(value);notes[index]=[...set].sort();return{...state,notes,lightHint:null}}const values=[...state.values],notes=state.notes.map(list=>[...list]);values[index]=value;notes[index]=[];for(const peer of peers(index))notes[peer]=notes[peer].filter(n=>n!==value);return{...state,values,notes,lightHint:null}}
export function clearCell(puzzle:SudokuPuzzle,state:SudokuState){const index=state.selected;if(index===null||isFixed(puzzle,state,index))return state;const values=[...state.values],notes=state.notes.map(list=>[...list]);values[index]=0;notes[index]=[];return{...state,values,notes,lightHint:null}}
export function lightHint(state:SudokuState){if(state.selected===null)return state;const found=candidates(state.values,state.selected),signature=`${state.selected}:${state.values.join('')}`;if(state.lightHint?.signature===signature)return state;return{...state,lightHint:{index:state.selected,candidates:found,signature},hintCount:state.hintCount+1}}
export function revealHint(puzzle:SudokuPuzzle,state:SudokuState,preferred?:number){const eligible=state.values.map((v,i)=>({v,i})).filter(({v,i})=>puzzle.givens[i]===0&&!state.hinted.includes(i)&&v!==puzzle.solution[i]);if(!eligible.length)return state;const index=preferred!==undefined&&eligible.some(item=>item.i===preferred)?preferred:eligible[0].i,values=[...state.values],notes=state.notes.map(list=>[...list]);values[index]=puzzle.solution[index];notes[index]=[];for(const peer of peers(index))notes[peer]=notes[peer].filter(n=>n!==values[index]);return{...state,values,notes,hinted:[...state.hinted,index],hintCount:state.hintCount+1,selected:index,lightHint:null}}
export function validateGrid(values:number[],complete=false){if(values.length!==81||values.some(v=>!Number.isInteger(v)||v<0||v>9||(complete&&v===0)))return false;return conflicts(values).size===0}
