import { useEffect,useState } from 'react'
import './App.css'
import { settingsStore } from './common/storage/settings'
import { loadBundledPuzzles as loadLights } from './games/lights-out/data/puzzles'
import type { LightsOutPuzzle } from './games/lights-out/domain/lightsOut'
import { LightsOutGame } from './games/lights-out/ui/LightsOutGame'
import { LightsOutSetup } from './games/lights-out/ui/LightsOutSetup'
import { loadBundledPuzzles as loadFifteen } from './games/fifteen/data/puzzles'
import type { FifteenPuzzle } from './games/fifteen/domain/fifteen'
import { FifteenGame } from './games/fifteen/ui/FifteenGame'
import { FifteenSetup } from './games/fifteen/ui/FifteenSetup'

type GameId='lights_out'|'fifteen';type Screen='launcher'|'setup'|'game'
export default function App(){const[game,setGame]=useState<GameId|null>(null),[screen,setScreen]=useState<Screen>('launcher'),[lights,setLights]=useState<LightsOutPuzzle[]>([]),[fifteen,setFifteen]=useState<FifteenPuzzle[]>([]),[selectedLights,setSelectedLights]=useState<LightsOutPuzzle|null>(null),[selectedFifteen,setSelectedFifteen]=useState<FifteenPuzzle|null>(null),[error,setError]=useState('');useEffect(()=>{Promise.all([loadLights(),loadFifteen()]).then(([lightsData,fifteenData])=>{setLights(lightsData);setFifteen(fifteenData)}).catch((reason:unknown)=>setError(reason instanceof Error?reason.message:'問題データを読み込めません。'))},[]);useEffect(()=>settingsStore.set({lastGame:game}),[game]);const launcher=()=>{setGame(null);setScreen('launcher')};const open=(id:GameId)=>{setGame(id);setScreen('setup')};if(error)return <main className="shell"><section className="panel error"><h1>読込エラー</h1><p>{error}</p></section></main>;if(game==='lights_out'&&screen==='game'&&selectedLights)return <LightsOutGame puzzle={selectedLights} onBack={()=>setScreen('setup')} onLauncher={launcher}/>;if(game==='lights_out'&&screen==='setup')return <LightsOutSetup puzzles={lights} onStart={p=>{setSelectedLights(p);setScreen('game')}} onLauncher={launcher}/>;if(game==='fifteen'&&screen==='game'&&selectedFifteen)return <FifteenGame puzzle={selectedFifteen} onBack={()=>setScreen('setup')} onLauncher={launcher}/>;if(game==='fifteen'&&screen==='setup')return <FifteenSetup puzzles={fifteen} onStart={p=>{setSelectedFifteen(p);setScreen('game')}} onLauncher={launcher}/>;return <main className="shell"><section className="hero-card"><p className="eyebrow">THINK • PLAY • RELAX</p><h1>TypeScript パズルゲーム集</h1><p>少し頭を使う、盤面型パズルのコレクション</p></section><section className="catalog"><button className="game-card" onClick={()=>open('lights_out')}><span className="game-icon">✦</span><span><strong>ライツアウト</strong><small>光るマスをすべて消そう</small></span><b>遊ぶ →</b></button><button className="game-card fifteen-card" onClick={()=>open('fifteen')}><span className="game-icon">15</span><span><strong>15パズル</strong><small>駒を順番に並べよう</small></span><b>遊ぶ →</b></button><div className="coming-soon">ほかのゲームは順次移植します</div></section></main>}
