import { describe,expect,it } from "vitest";
import { analyzeHypothesis,applyHypothesisSequence,commitHypothesis,countCompletions,candidates,conflicts,countSolutions,hypothesisSequences,initialSkyscraper,isComplete,lineCandidates,selectHypothesisLine,startHypothesis,undoHypothesis,visibleCount,visibilityMarkers,workingValues,type SkyscraperPuzzle } from "../domain/skyscraper";
const puzzle:SkyscraperPuzzle={id:"test",title:"test",difficulty:"easy",size:4,clues:{top:[4,3,2,1],right:[1,2,2,2],bottom:[1,2,2,2],left:[4,3,2,1]},givens:Array(16).fill(0),solution:[1,2,3,4,2,3,4,1,3,4,1,2,4,1,2,3]};
describe("skyscraper domain",()=>{
  it("counts buildings from the viewing edge",()=>expect(visibleCount([2,1,4,3])).toBe(2));
  it("distinguishes confirmed and provisional markers",()=>{const markers=visibilityMarkers([2,0,4,3],4,"left",0);expect(markers.get(0)).toBe("confirmed");expect(markers.get(2)).toBe("provisional")});
  it("filters permutations with both clues",()=>expect(lineCandidates([0,0,0,0],4,1)).toEqual([[1,2,3,4]]));
  it("uses row, column and clues for cell candidates",()=>expect(candidates(puzzle,puzzle.givens,0)).toEqual([1]));
  it("detects row and column duplicates",()=>expect([...conflicts([1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0],4)].sort()).toEqual([0,1,4]));
  it("accepts a constraint-complete grid and has one solution",()=>{const state={...initialSkyscraper(puzzle),values:[...puzzle.solution]};expect(isComplete(puzzle,state)).toBe(true);expect(countSolutions(puzzle)).toBe(1)});
  it("enumerates note-compatible line hypotheses without changing confirmed values",()=>{let state=startHypothesis(initialSkyscraper(puzzle)),line={axis:"row" as const,unit:0};state=selectHypothesisLine(state,line);expect(hypothesisSequences(puzzle,state,line)).toEqual([[1,2,3,4]]);state=applyHypothesisSequence(puzzle,state,line,[1,2,3,4]);expect(state.values).toEqual(Array(16).fill(0));expect(workingValues(state).slice(0,4)).toEqual([1,2,3,4]);expect(state.hypothesis?.history).toHaveLength(1);expect(workingValues(undoHypothesis(state)).slice(0,4)).toEqual([0,0,0,0])});
  it("propagates line domains, detects contradictions and commits trials",()=>{let state=startHypothesis(initialSkyscraper(puzzle));expect(analyzeHypothesis(puzzle,state).forced.length).toBeGreaterThan(0);state={...state,selected:0};state=applyHypothesisSequence(puzzle,state,{axis:"row",unit:0},[4,3,2,1]);expect(analyzeHypothesis(puzzle,state).contradiction).not.toBeNull();expect(countCompletions(puzzle,state)).toBe(0);state=undoHypothesis(state);state=applyHypothesisSequence(puzzle,state,{axis:"row",unit:0},[1,2,3,4]);const committed=commitHypothesis(state);expect(committed.hypothesis).toBeNull();expect(committed.values.slice(0,4)).toEqual([1,2,3,4])});
  it("keeps a five-cell unconstrained line bounded to 120 arrangements",()=>{const open:SkyscraperPuzzle={...puzzle,size:5,clues:{top:[0,0,0,0,0],right:[0,0,0,0,0],bottom:[0,0,0,0,0],left:[0,0,0,0,0]},givens:Array(25).fill(0),solution:Array(25).fill(1)},state=startHypothesis(initialSkyscraper(open));expect(hypothesisSequences(open,state,{axis:"row",unit:0})).toHaveLength(120)});
});
